# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Utilisateur/Documents/Cours/Architect/TP1/TP1.srcs/sources_1/bd/design_tp1/ip/design_tp1_hardware_accelerator_0_0/design_tp1_hardware_accelerator_0_0.xci
# IP: The module: 'design_tp1_hardware_accelerator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Utilisateur/Documents/Cours/Architect/TP1/TP1.srcs/sources_1/bd/design_tp1/ip/design_tp1_hardware_accelerator_0_0/constraints/hardware_accelerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tp1_hardware_accelerator_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Utilisateur/Documents/Cours/Architect/TP1/TP1.srcs/sources_1/bd/design_tp1/ip/design_tp1_hardware_accelerator_0_0/design_tp1_hardware_accelerator_0_0.xci
# IP: The module: 'design_tp1_hardware_accelerator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Utilisateur/Documents/Cours/Architect/TP1/TP1.srcs/sources_1/bd/design_tp1/ip/design_tp1_hardware_accelerator_0_0/constraints/hardware_accelerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_tp1_hardware_accelerator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
