# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_tp1/design_tp1.bd
# Block Designs: The module: 'design_tp1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/design_tp1/ip/design_tp1_processing_system7_0_0/design_tp1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_processing_system7_0_0 || ORIG_REF_NAME==design_tp1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_proc_sys_reset_0_0/design_tp1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_tp1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_axi_dma_0_0/design_tp1_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_axi_dma_0_0 || ORIG_REF_NAME==design_tp1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_ps7_0_axi_periph_0/design_tp1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_tp1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_xbar_0/design_tp1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_xbar_0 || ORIG_REF_NAME==design_tp1_xbar_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_axi_interconnect_0_0/design_tp1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_axi_interconnect_0_0 || ORIG_REF_NAME==design_tp1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_xlconcat_0_0/design_tp1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_xlconcat_0_0 || ORIG_REF_NAME==design_tp1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_xlconstant_0_0/design_tp1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_xlconstant_0_0 || ORIG_REF_NAME==design_tp1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_hardware_accelerator_0_0/design_tp1_hardware_accelerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_hardware_accelerator_0_0 || ORIG_REF_NAME==design_tp1_hardware_accelerator_0_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_auto_pc_0/design_tp1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_auto_pc_0 || ORIG_REF_NAME==design_tp1_auto_pc_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_auto_us_0/design_tp1_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_auto_us_0 || ORIG_REF_NAME==design_tp1_auto_us_0} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_auto_us_1/design_tp1_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_auto_us_1 || ORIG_REF_NAME==design_tp1_auto_us_1} -quiet] -quiet

# IP: bd/design_tp1/ip/design_tp1_auto_pc_1/design_tp1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_tp1_auto_pc_1 || ORIG_REF_NAME==design_tp1_auto_pc_1} -quiet] -quiet

# XDC: bd/design_tp1/design_tp1_ooc.xdc
